lead/urls.py
from django.urls import path

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
]

tealcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from userprofile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team/urls.py
from django.urls import path

from . import views

app_name = 'team'

urlpatterns = [
    path('', views.teams_list, name='list'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit_team, name='edit'),
    path('<int:pk>/activate/', views.teams_activate, name='activate'),
]

team/models.py
from django.contrib.auth.models import User
from django.db import models

class Plan(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    description = models.TextField(blank=True, null=True)
    max_leads = models.IntegerField()
    max_clients = models.IntegerField()

    def __str__(self):
        return self.name

class Team(models.Model):
    plan = models.ForeignKey(Plan, related_name='teams', blank=True, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    members = models.ManyToManyField(User, related_name='teams')
    created_by = models.ForeignKey(User, related_name='created_teams', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    def get_plan(self):
        if self.plan:
            return self.plan
        else:
            if Plan.objects.count() > 0:
                self.plan = Plan.objects.all().first()
                self.save()
            else:
                plan = Plan.objects.create(name='Free', price=0, max_leads=3, max_clients=3)
                self.plan = plan
                self.save()

            return self.plan
            

team/forms.py
from django import forms

from .models import Team

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ('name',)

team/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from .forms import TeamForm
from .models import Team


@login_required
def teams_list(request):
    teams = Team.objects.filter(members__in=[request.user])

    return render(request, 'team/teams_list.html', {'teams': teams})


@login_required
def teams_activate(request, pk):
    team = Team.objects.filter(members__in=[request.user]).get(pk=pk)
    userprofile = request.user.userprofile
    userprofile.active_team = team
    userprofile.save()

    return redirect('team:detail', pk=pk)


@login_required
def detail(request, pk):
    team = get_object_or_404(Team, members__in=[request.user], pk=pk)

    return render(request, 'team/detail.html', {'team': team})


@login_required
def edit_team(request, pk):
    team = get_object_or_404(Team, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = TeamForm(request.POST, instance=team)

        if form.is_valid():
            form.save()

            messages.success(request, 'The changes was saved!')

            return redirect('userprofile:myaccount')
    else:
        form = TeamForm(instance=team)

    return render(request, 'team/edit_team.html', {
        'team': team,
        'form': form
    })

team/templates/team/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ team.name }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-6 text-xl">{{ team.name }}</h1>

        <a href="{% url 'team:list' %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl text-white">Поменять
            предприятие</a>

        {% if team.created_by == request.user %}
            <a href="{% url 'team:edit' team.id %}" class="inline-block py-4 px-6 bg-sky-600 rounded-xl text-white">
                Изменить</a>
        {% endif %}

        <p class="mt-6"><strong>Владелец предприятия:</strong> {{ team.created_by }}</p>

        <hr class="my-4">

        <h2 class="font-semibold">Участники:</h2>

        {% for member in team.members.all %}
            <p>{{ member.username }}</p>
        {% endfor %}
    </div>
{% endblock %}

team/templates/team/edit_team.html
{% extends 'core/base.html' %}

{% block title %}Редактировать команду - ({{ team.name }}){% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">Редактировать команду - ({{ team.name }})</h1>

        <form method="post" action=".">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Сохранить</button>
        </form>
    </div>
{% endblock %}

team/templates/team/teams_list.html
{% extends 'core/base.html' %}

{% block title %}Команды{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-6 text-2xl">Команды</h1>

        <div class="grid grid-cols-4 gap-4">
            {% for team in teams %}
                <div class="{% if team == active_team %}bg-emerald-100{% else %}bg-gray-100{% endif %} rounded-xl p-6">
                    <h2 class="mb-4 text-xl">{{ team.name }}</h2>

                    {% if team == active_team %}
                        <a href="{% url 'team:detail' team.id %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl text-white">Подробнее</a>
                    {% else %}
                        <a href="{% url 'team:activate' team.id %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl text-white">Выбрать предприятие</a>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}